/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.MyAtlProjectRuntimeModule;
import org.xtext.example.mydsl.MyAtlProjectStandaloneSetup;
import org.xtext.example.mydsl.ide.MyAtlProjectIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MyAtlProjectIdeSetup extends MyAtlProjectStandaloneSetup {
  @Override
  public Injector createInjector() {
    MyAtlProjectRuntimeModule _myAtlProjectRuntimeModule = new MyAtlProjectRuntimeModule();
    MyAtlProjectIdeModule _myAtlProjectIdeModule = new MyAtlProjectIdeModule();
    return Guice.createInjector(Modules2.mixin(_myAtlProjectRuntimeModule, _myAtlProjectIdeModule));
  }
}
