/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl.ide;

import org.xtext.example.mydsl.ide.AbstractMyAtlProjectIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyAtlProjectIdeModule extends AbstractMyAtlProjectIdeModule {
}
