/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myOcl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context Decl CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myOcl.ContextDeclCS#getOwnedPathName <em>Owned Path Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getContextDeclCS()
 * @model
 * @generated
 */
public interface ContextDeclCS extends EObject
{
  /**
   * Returns the value of the '<em><b>Owned Path Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Path Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Path Name</em>' containment reference.
   * @see #setOwnedPathName(pathNameCS)
   * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getContextDeclCS_OwnedPathName()
   * @model containment="true"
   * @generated
   */
  pathNameCS getOwnedPathName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myOcl.ContextDeclCS#getOwnedPathName <em>Owned Path Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Path Name</em>' containment reference.
   * @see #getOwnedPathName()
   * @generated
   */
  void setOwnedPathName(pathNameCS value);

} // ContextDeclCS
