/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myOcl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Def Property CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getDefPropertyCS()
 * @model
 * @generated
 */
public interface DefPropertyCS extends DefCS
{
} // DefPropertyCS
