/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myOcl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prefixed Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getPrefixedExpCS()
 * @model
 * @generated
 */
public interface PrefixedExpCS extends InfixedExpCS
{
} // PrefixedExpCS
