/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.MyOclStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyOclStandaloneSetup extends MyOclStandaloneSetupGenerated {
  public static void doSetup() {
    new MyOclStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
