/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myAtl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myAtl.ExpCS;
import org.xtext.example.mydsl.myAtl.MyAtlPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExpCSImpl extends NavigatingArgExpCSImpl implements ExpCS
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpCSImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyAtlPackage.Literals.EXP_CS;
  }

} //ExpCSImpl
