/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MyAtlProjectStandaloneSetup extends MyAtlProjectStandaloneSetupGenerated {

	def static void doSetup() {
		new MyAtlProjectStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
