/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl.tests;

import ocl.OclExpression;
import org.xtext.example.mydsl.tests.MyDslInjectorProvider;

/* @RunWith(/* name is null */)
@InjectWith(MyDslInjectorProvider.class) */@SuppressWarnings("all")
public class MyDslParsingTest {
  /* @Inject
   */private /* ParseHelper<OclExpression> */Object parseHelper;
  
  /* @Test
   */public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Assert is undefined"
      + "\nThe method or field Assert is undefined"
      + "\nThe field MyDslParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\nassertNotNull cannot be resolved"
      + "\nassertTrue cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
