/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.MyAtlRuntimeModule;
import org.xtext.example.mydsl.MyAtlStandaloneSetup;
import org.xtext.example.mydsl.ide.MyAtlIdeModule;
import org.xtext.example.mydsl.web.MyAtlWebModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class MyAtlWebSetup extends MyAtlStandaloneSetup {
  @Override
  public Injector createInjector() {
    MyAtlRuntimeModule _myAtlRuntimeModule = new MyAtlRuntimeModule();
    MyAtlIdeModule _myAtlIdeModule = new MyAtlIdeModule();
    MyAtlWebModule _myAtlWebModule = new MyAtlWebModule();
    return Guice.createInjector(Modules2.mixin(_myAtlRuntimeModule, _myAtlIdeModule, _myAtlWebModule));
  }
}
