/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.myatl2.ui.internal.Myatl2Activator;

public class MyAtlProjectUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Myatl2Activator.getInstance().getInjector("org.xtext.example.mydsl.MyAtlProject");
	}

}
