/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.atl.ui.internal.AtlActivator;

public class MyAtlProjectUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AtlActivator.getInstance().getInjector("org.xtext.example.mydsl.MyAtlProject");
	}

}
