/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myATL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myATL.MyATLPackage;
import org.xtext.example.mydsl.myATL.PrimaryExpCS;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Primary Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PrimaryExpCSImpl extends PrefixedExpCSImpl implements PrimaryExpCS
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrimaryExpCSImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyATLPackage.Literals.PRIMARY_EXP_CS;
  }

} //PrimaryExpCSImpl
