/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myOcl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Def Operation CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myOcl.DefOperationCS#getOwnedSignature <em>Owned Signature</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myOcl.DefOperationCS#getOwnedParameters <em>Owned Parameters</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getDefOperationCS()
 * @model
 * @generated
 */
public interface DefOperationCS extends DefCS
{
  /**
   * Returns the value of the '<em><b>Owned Signature</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Signature</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Signature</em>' containment reference.
   * @see #setOwnedSignature(TemplateSignatureCS)
   * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getDefOperationCS_OwnedSignature()
   * @model containment="true"
   * @generated
   */
  TemplateSignatureCS getOwnedSignature();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myOcl.DefOperationCS#getOwnedSignature <em>Owned Signature</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Signature</em>' containment reference.
   * @see #getOwnedSignature()
   * @generated
   */
  void setOwnedSignature(TemplateSignatureCS value);

  /**
   * Returns the value of the '<em><b>Owned Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myOcl.DefParameterCS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Parameters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Parameters</em>' containment reference list.
   * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getDefOperationCS_OwnedParameters()
   * @model containment="true"
   * @generated
   */
  EList<DefParameterCS> getOwnedParameters();

} // DefOperationCS
