/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myOcl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Infix Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myOcl.InfixExpCS#getOwnedExpression <em>Owned Expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myOcl.InfixExpCS#getOwnedOperator <em>Owned Operator</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getInfixExpCS()
 * @model
 * @generated
 */
public interface InfixExpCS extends InfixedExpCS
{
  /**
   * Returns the value of the '<em><b>Owned Expression</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myOcl.PrefixedExpCS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Expression</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Expression</em>' containment reference list.
   * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getInfixExpCS_OwnedExpression()
   * @model containment="true"
   * @generated
   */
  EList<PrefixedExpCS> getOwnedExpression();

  /**
   * Returns the value of the '<em><b>Owned Operator</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myOcl.BinaryOperatorCS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Operator</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Operator</em>' containment reference list.
   * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getInfixExpCS_OwnedOperator()
   * @model containment="true"
   * @generated
   */
  EList<BinaryOperatorCS> getOwnedOperator();

} // InfixExpCS
