/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myOcl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Let Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myOcl.LetExpCS#getVariable <em>Variable</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myOcl.LetExpCS#getIn <em>In</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getLetExpCS()
 * @model
 * @generated
 */
public interface LetExpCS extends PrimaryExpCS
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myOcl.LetVariableCS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference list.
   * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getLetExpCS_Variable()
   * @model containment="true"
   * @generated
   */
  EList<LetVariableCS> getVariable();

  /**
   * Returns the value of the '<em><b>In</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>In</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>In</em>' containment reference.
   * @see #setIn(ExpCS)
   * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getLetExpCS_In()
   * @model containment="true"
   * @generated
   */
  ExpCS getIn();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myOcl.LetExpCS#getIn <em>In</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>In</em>' containment reference.
   * @see #getIn()
   * @generated
   */
  void setIn(ExpCS value);

} // LetExpCS
