/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myOcl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Package Declaration CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myOcl.PackageDeclarationCS#getOwnedPathName <em>Owned Path Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myOcl.PackageDeclarationCS#getOwnedInvariants <em>Owned Invariants</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myOcl.PackageDeclarationCS#getOwnedContexts <em>Owned Contexts</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getPackageDeclarationCS()
 * @model
 * @generated
 */
public interface PackageDeclarationCS extends EObject
{
  /**
   * Returns the value of the '<em><b>Owned Path Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Path Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Path Name</em>' containment reference.
   * @see #setOwnedPathName(pathNameCS)
   * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getPackageDeclarationCS_OwnedPathName()
   * @model containment="true"
   * @generated
   */
  pathNameCS getOwnedPathName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myOcl.PackageDeclarationCS#getOwnedPathName <em>Owned Path Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Path Name</em>' containment reference.
   * @see #getOwnedPathName()
   * @generated
   */
  void setOwnedPathName(pathNameCS value);

  /**
   * Returns the value of the '<em><b>Owned Invariants</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myOcl.ConstraintCS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Invariants</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Invariants</em>' containment reference list.
   * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getPackageDeclarationCS_OwnedInvariants()
   * @model containment="true"
   * @generated
   */
  EList<ConstraintCS> getOwnedInvariants();

  /**
   * Returns the value of the '<em><b>Owned Contexts</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myOcl.ContextDeclCS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Contexts</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Contexts</em>' containment reference list.
   * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getPackageDeclarationCS_OwnedContexts()
   * @model containment="true"
   * @generated
   */
  EList<ContextDeclCS> getOwnedContexts();

} // PackageDeclarationCS
