/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myOcl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Context Decl CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myOcl.PropertyContextDeclCS#getOwnedType <em>Owned Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myOcl.PropertyContextDeclCS#getOwnedDerivedInvariants <em>Owned Derived Invariants</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myOcl.PropertyContextDeclCS#getOwnedDefaultExpressions <em>Owned Default Expressions</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getPropertyContextDeclCS()
 * @model
 * @generated
 */
public interface PropertyContextDeclCS extends ContextDeclCS
{
  /**
   * Returns the value of the '<em><b>Owned Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Type</em>' containment reference.
   * @see #setOwnedType(TypeExpCS)
   * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getPropertyContextDeclCS_OwnedType()
   * @model containment="true"
   * @generated
   */
  TypeExpCS getOwnedType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myOcl.PropertyContextDeclCS#getOwnedType <em>Owned Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Type</em>' containment reference.
   * @see #getOwnedType()
   * @generated
   */
  void setOwnedType(TypeExpCS value);

  /**
   * Returns the value of the '<em><b>Owned Derived Invariants</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myOcl.ConstraintCS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Derived Invariants</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Derived Invariants</em>' containment reference list.
   * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getPropertyContextDeclCS_OwnedDerivedInvariants()
   * @model containment="true"
   * @generated
   */
  EList<ConstraintCS> getOwnedDerivedInvariants();

  /**
   * Returns the value of the '<em><b>Owned Default Expressions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myOcl.SpecificationCS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Default Expressions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Default Expressions</em>' containment reference list.
   * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getPropertyContextDeclCS_OwnedDefaultExpressions()
   * @model containment="true"
   * @generated
   */
  EList<SpecificationCS> getOwnedDefaultExpressions();

} // PropertyContextDeclCS
