/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myOcl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Parameter CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getTypeParameterCS()
 * @model
 * @generated
 */
public interface TypeParameterCS extends EObject
{
} // TypeParameterCS
