/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myOcl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Literal Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myOcl.TypeLiteralExpCS#getOwnedType <em>Owned Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getTypeLiteralExpCS()
 * @model
 * @generated
 */
public interface TypeLiteralExpCS extends EObject
{
  /**
   * Returns the value of the '<em><b>Owned Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Type</em>' containment reference.
   * @see #setOwnedType(TypeLiteralCS)
   * @see org.xtext.example.mydsl.myOcl.MyOclPackage#getTypeLiteralExpCS_OwnedType()
   * @model containment="true"
   * @generated
   */
  TypeLiteralCS getOwnedType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myOcl.TypeLiteralExpCS#getOwnedType <em>Owned Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Type</em>' containment reference.
   * @see #getOwnedType()
   * @generated
   */
  void setOwnedType(TypeLiteralCS value);

} // TypeLiteralExpCS
