/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalMyOclParser;
import org.xtext.example.mydsl.services.MyOclGrammarAccess;

public class MyOclParser extends AbstractAntlrParser {

	@Inject
	private MyOclGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMyOclParser createParser(XtextTokenStream stream) {
		return new InternalMyOclParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "CompleteOCLDocumentCS";
	}

	public MyOclGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyOclGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
