/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl.ide;

import org.xtext.example.mydsl.MyDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MyDslIdeSetup extends MyDslStandaloneSetup {
  @Override
  public Object createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Guice is undefined"
      + "\nThe method or field Modules2 is undefined"
      + "\ncreateInjector cannot be resolved"
      + "\nmixin cannot be resolved");
  }
}
