/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myAtl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unlimited Natural Literal Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myAtl.MyAtlPackage#getUnlimitedNaturalLiteralExpCS()
 * @model
 * @generated
 */
public interface UnlimitedNaturalLiteralExpCS extends PrimitiveLiteralExpCS
{
} // UnlimitedNaturalLiteralExpCS
