/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myOcl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myOcl.DefOperationCS;
import org.xtext.example.mydsl.myOcl.DefParameterCS;
import org.xtext.example.mydsl.myOcl.MyOclPackage;
import org.xtext.example.mydsl.myOcl.TemplateSignatureCS;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Def Operation CS</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myOcl.impl.DefOperationCSImpl#getOwnedSignature <em>Owned Signature</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myOcl.impl.DefOperationCSImpl#getOwnedParameters <em>Owned Parameters</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DefOperationCSImpl extends DefCSImpl implements DefOperationCS
{
  /**
   * The cached value of the '{@link #getOwnedSignature() <em>Owned Signature</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedSignature()
   * @generated
   * @ordered
   */
  protected TemplateSignatureCS ownedSignature;

  /**
   * The cached value of the '{@link #getOwnedParameters() <em>Owned Parameters</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedParameters()
   * @generated
   * @ordered
   */
  protected EList<DefParameterCS> ownedParameters;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DefOperationCSImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyOclPackage.Literals.DEF_OPERATION_CS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TemplateSignatureCS getOwnedSignature()
  {
    return ownedSignature;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOwnedSignature(TemplateSignatureCS newOwnedSignature, NotificationChain msgs)
  {
    TemplateSignatureCS oldOwnedSignature = ownedSignature;
    ownedSignature = newOwnedSignature;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyOclPackage.DEF_OPERATION_CS__OWNED_SIGNATURE, oldOwnedSignature, newOwnedSignature);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOwnedSignature(TemplateSignatureCS newOwnedSignature)
  {
    if (newOwnedSignature != ownedSignature)
    {
      NotificationChain msgs = null;
      if (ownedSignature != null)
        msgs = ((InternalEObject)ownedSignature).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyOclPackage.DEF_OPERATION_CS__OWNED_SIGNATURE, null, msgs);
      if (newOwnedSignature != null)
        msgs = ((InternalEObject)newOwnedSignature).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyOclPackage.DEF_OPERATION_CS__OWNED_SIGNATURE, null, msgs);
      msgs = basicSetOwnedSignature(newOwnedSignature, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyOclPackage.DEF_OPERATION_CS__OWNED_SIGNATURE, newOwnedSignature, newOwnedSignature));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<DefParameterCS> getOwnedParameters()
  {
    if (ownedParameters == null)
    {
      ownedParameters = new EObjectContainmentEList<DefParameterCS>(DefParameterCS.class, this, MyOclPackage.DEF_OPERATION_CS__OWNED_PARAMETERS);
    }
    return ownedParameters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyOclPackage.DEF_OPERATION_CS__OWNED_SIGNATURE:
        return basicSetOwnedSignature(null, msgs);
      case MyOclPackage.DEF_OPERATION_CS__OWNED_PARAMETERS:
        return ((InternalEList<?>)getOwnedParameters()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyOclPackage.DEF_OPERATION_CS__OWNED_SIGNATURE:
        return getOwnedSignature();
      case MyOclPackage.DEF_OPERATION_CS__OWNED_PARAMETERS:
        return getOwnedParameters();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyOclPackage.DEF_OPERATION_CS__OWNED_SIGNATURE:
        setOwnedSignature((TemplateSignatureCS)newValue);
        return;
      case MyOclPackage.DEF_OPERATION_CS__OWNED_PARAMETERS:
        getOwnedParameters().clear();
        getOwnedParameters().addAll((Collection<? extends DefParameterCS>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyOclPackage.DEF_OPERATION_CS__OWNED_SIGNATURE:
        setOwnedSignature((TemplateSignatureCS)null);
        return;
      case MyOclPackage.DEF_OPERATION_CS__OWNED_PARAMETERS:
        getOwnedParameters().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyOclPackage.DEF_OPERATION_CS__OWNED_SIGNATURE:
        return ownedSignature != null;
      case MyOclPackage.DEF_OPERATION_CS__OWNED_PARAMETERS:
        return ownedParameters != null && !ownedParameters.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //DefOperationCSImpl
