/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myOcl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myOcl.InfixOperatorCS;
import org.xtext.example.mydsl.myOcl.MyOclPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Infix Operator CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InfixOperatorCSImpl extends BinaryOperatorCSImpl implements InfixOperatorCS
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InfixOperatorCSImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyOclPackage.Literals.INFIX_OPERATOR_CS;
  }

} //InfixOperatorCSImpl
