/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myOcl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myOcl.MyOclPackage;
import org.xtext.example.mydsl.myOcl.TemplateSignatureCS;
import org.xtext.example.mydsl.myOcl.TypeParameterCS;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Template Signature CS</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myOcl.impl.TemplateSignatureCSImpl#getOwnedParameters <em>Owned Parameters</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TemplateSignatureCSImpl extends MinimalEObjectImpl.Container implements TemplateSignatureCS
{
  /**
   * The cached value of the '{@link #getOwnedParameters() <em>Owned Parameters</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedParameters()
   * @generated
   * @ordered
   */
  protected EList<TypeParameterCS> ownedParameters;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TemplateSignatureCSImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyOclPackage.Literals.TEMPLATE_SIGNATURE_CS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<TypeParameterCS> getOwnedParameters()
  {
    if (ownedParameters == null)
    {
      ownedParameters = new EObjectContainmentEList<TypeParameterCS>(TypeParameterCS.class, this, MyOclPackage.TEMPLATE_SIGNATURE_CS__OWNED_PARAMETERS);
    }
    return ownedParameters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyOclPackage.TEMPLATE_SIGNATURE_CS__OWNED_PARAMETERS:
        return ((InternalEList<?>)getOwnedParameters()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyOclPackage.TEMPLATE_SIGNATURE_CS__OWNED_PARAMETERS:
        return getOwnedParameters();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyOclPackage.TEMPLATE_SIGNATURE_CS__OWNED_PARAMETERS:
        getOwnedParameters().clear();
        getOwnedParameters().addAll((Collection<? extends TypeParameterCS>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyOclPackage.TEMPLATE_SIGNATURE_CS__OWNED_PARAMETERS:
        getOwnedParameters().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyOclPackage.TEMPLATE_SIGNATURE_CS__OWNED_PARAMETERS:
        return ownedParameters != null && !ownedParameters.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //TemplateSignatureCSImpl
