/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.MyOclRuntimeModule;
import org.xtext.example.mydsl.MyOclStandaloneSetup;
import org.xtext.example.mydsl.ide.MyOclIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MyOclIdeSetup extends MyOclStandaloneSetup {
  @Override
  public Injector createInjector() {
    MyOclRuntimeModule _myOclRuntimeModule = new MyOclRuntimeModule();
    MyOclIdeModule _myOclIdeModule = new MyOclIdeModule();
    return Guice.createInjector(Modules2.mixin(_myOclRuntimeModule, _myOclIdeModule));
  }
}
