/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myOcl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myOcl.MyOclPackage;
import org.xtext.example.mydsl.myOcl.NavigatingArgExpCS;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Navigating Arg Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NavigatingArgExpCSImpl extends MinimalEObjectImpl.Container implements NavigatingArgExpCS
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NavigatingArgExpCSImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyOclPackage.Literals.NAVIGATING_ARG_EXP_CS;
  }

} //NavigatingArgExpCSImpl
