/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myOcl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myOcl.ConstraintCS;
import org.xtext.example.mydsl.myOcl.MyOclPackage;
import org.xtext.example.mydsl.myOcl.OperationContextDeclCS;
import org.xtext.example.mydsl.myOcl.ParameterCS;
import org.xtext.example.mydsl.myOcl.SpecificationCS;
import org.xtext.example.mydsl.myOcl.TemplateSignatureCS;
import org.xtext.example.mydsl.myOcl.TypeExpCS;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Operation Context Decl CS</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myOcl.impl.OperationContextDeclCSImpl#getOwnedSignature <em>Owned Signature</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myOcl.impl.OperationContextDeclCSImpl#getOwnedParameters <em>Owned Parameters</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myOcl.impl.OperationContextDeclCSImpl#getOwnedType <em>Owned Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myOcl.impl.OperationContextDeclCSImpl#getOwnedPreconditions <em>Owned Preconditions</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myOcl.impl.OperationContextDeclCSImpl#getOwnedPostconditions <em>Owned Postconditions</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myOcl.impl.OperationContextDeclCSImpl#getOwnedBodies <em>Owned Bodies</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OperationContextDeclCSImpl extends ContextDeclCSImpl implements OperationContextDeclCS
{
  /**
   * The cached value of the '{@link #getOwnedSignature() <em>Owned Signature</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedSignature()
   * @generated
   * @ordered
   */
  protected TemplateSignatureCS ownedSignature;

  /**
   * The cached value of the '{@link #getOwnedParameters() <em>Owned Parameters</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedParameters()
   * @generated
   * @ordered
   */
  protected EList<ParameterCS> ownedParameters;

  /**
   * The cached value of the '{@link #getOwnedType() <em>Owned Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedType()
   * @generated
   * @ordered
   */
  protected TypeExpCS ownedType;

  /**
   * The cached value of the '{@link #getOwnedPreconditions() <em>Owned Preconditions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedPreconditions()
   * @generated
   * @ordered
   */
  protected EList<ConstraintCS> ownedPreconditions;

  /**
   * The cached value of the '{@link #getOwnedPostconditions() <em>Owned Postconditions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedPostconditions()
   * @generated
   * @ordered
   */
  protected EList<ConstraintCS> ownedPostconditions;

  /**
   * The cached value of the '{@link #getOwnedBodies() <em>Owned Bodies</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedBodies()
   * @generated
   * @ordered
   */
  protected EList<SpecificationCS> ownedBodies;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OperationContextDeclCSImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyOclPackage.Literals.OPERATION_CONTEXT_DECL_CS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TemplateSignatureCS getOwnedSignature()
  {
    return ownedSignature;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOwnedSignature(TemplateSignatureCS newOwnedSignature, NotificationChain msgs)
  {
    TemplateSignatureCS oldOwnedSignature = ownedSignature;
    ownedSignature = newOwnedSignature;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_SIGNATURE, oldOwnedSignature, newOwnedSignature);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOwnedSignature(TemplateSignatureCS newOwnedSignature)
  {
    if (newOwnedSignature != ownedSignature)
    {
      NotificationChain msgs = null;
      if (ownedSignature != null)
        msgs = ((InternalEObject)ownedSignature).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_SIGNATURE, null, msgs);
      if (newOwnedSignature != null)
        msgs = ((InternalEObject)newOwnedSignature).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_SIGNATURE, null, msgs);
      msgs = basicSetOwnedSignature(newOwnedSignature, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_SIGNATURE, newOwnedSignature, newOwnedSignature));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ParameterCS> getOwnedParameters()
  {
    if (ownedParameters == null)
    {
      ownedParameters = new EObjectContainmentEList<ParameterCS>(ParameterCS.class, this, MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_PARAMETERS);
    }
    return ownedParameters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TypeExpCS getOwnedType()
  {
    return ownedType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOwnedType(TypeExpCS newOwnedType, NotificationChain msgs)
  {
    TypeExpCS oldOwnedType = ownedType;
    ownedType = newOwnedType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_TYPE, oldOwnedType, newOwnedType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOwnedType(TypeExpCS newOwnedType)
  {
    if (newOwnedType != ownedType)
    {
      NotificationChain msgs = null;
      if (ownedType != null)
        msgs = ((InternalEObject)ownedType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_TYPE, null, msgs);
      if (newOwnedType != null)
        msgs = ((InternalEObject)newOwnedType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_TYPE, null, msgs);
      msgs = basicSetOwnedType(newOwnedType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_TYPE, newOwnedType, newOwnedType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ConstraintCS> getOwnedPreconditions()
  {
    if (ownedPreconditions == null)
    {
      ownedPreconditions = new EObjectContainmentEList<ConstraintCS>(ConstraintCS.class, this, MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_PRECONDITIONS);
    }
    return ownedPreconditions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ConstraintCS> getOwnedPostconditions()
  {
    if (ownedPostconditions == null)
    {
      ownedPostconditions = new EObjectContainmentEList<ConstraintCS>(ConstraintCS.class, this, MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_POSTCONDITIONS);
    }
    return ownedPostconditions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<SpecificationCS> getOwnedBodies()
  {
    if (ownedBodies == null)
    {
      ownedBodies = new EObjectContainmentEList<SpecificationCS>(SpecificationCS.class, this, MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_BODIES);
    }
    return ownedBodies;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_SIGNATURE:
        return basicSetOwnedSignature(null, msgs);
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_PARAMETERS:
        return ((InternalEList<?>)getOwnedParameters()).basicRemove(otherEnd, msgs);
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_TYPE:
        return basicSetOwnedType(null, msgs);
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_PRECONDITIONS:
        return ((InternalEList<?>)getOwnedPreconditions()).basicRemove(otherEnd, msgs);
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_POSTCONDITIONS:
        return ((InternalEList<?>)getOwnedPostconditions()).basicRemove(otherEnd, msgs);
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_BODIES:
        return ((InternalEList<?>)getOwnedBodies()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_SIGNATURE:
        return getOwnedSignature();
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_PARAMETERS:
        return getOwnedParameters();
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_TYPE:
        return getOwnedType();
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_PRECONDITIONS:
        return getOwnedPreconditions();
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_POSTCONDITIONS:
        return getOwnedPostconditions();
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_BODIES:
        return getOwnedBodies();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_SIGNATURE:
        setOwnedSignature((TemplateSignatureCS)newValue);
        return;
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_PARAMETERS:
        getOwnedParameters().clear();
        getOwnedParameters().addAll((Collection<? extends ParameterCS>)newValue);
        return;
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_TYPE:
        setOwnedType((TypeExpCS)newValue);
        return;
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_PRECONDITIONS:
        getOwnedPreconditions().clear();
        getOwnedPreconditions().addAll((Collection<? extends ConstraintCS>)newValue);
        return;
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_POSTCONDITIONS:
        getOwnedPostconditions().clear();
        getOwnedPostconditions().addAll((Collection<? extends ConstraintCS>)newValue);
        return;
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_BODIES:
        getOwnedBodies().clear();
        getOwnedBodies().addAll((Collection<? extends SpecificationCS>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_SIGNATURE:
        setOwnedSignature((TemplateSignatureCS)null);
        return;
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_PARAMETERS:
        getOwnedParameters().clear();
        return;
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_TYPE:
        setOwnedType((TypeExpCS)null);
        return;
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_PRECONDITIONS:
        getOwnedPreconditions().clear();
        return;
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_POSTCONDITIONS:
        getOwnedPostconditions().clear();
        return;
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_BODIES:
        getOwnedBodies().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_SIGNATURE:
        return ownedSignature != null;
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_PARAMETERS:
        return ownedParameters != null && !ownedParameters.isEmpty();
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_TYPE:
        return ownedType != null;
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_PRECONDITIONS:
        return ownedPreconditions != null && !ownedPreconditions.isEmpty();
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_POSTCONDITIONS:
        return ownedPostconditions != null && !ownedPostconditions.isEmpty();
      case MyOclPackage.OPERATION_CONTEXT_DECL_CS__OWNED_BODIES:
        return ownedBodies != null && !ownedBodies.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //OperationContextDeclCSImpl
