/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.MyAtlRuntimeModule;
import org.xtext.example.mydsl.MyAtlStandaloneSetup;
import org.xtext.example.mydsl.ide.MyAtlIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MyAtlIdeSetup extends MyAtlStandaloneSetup {
  @Override
  public Injector createInjector() {
    MyAtlRuntimeModule _myAtlRuntimeModule = new MyAtlRuntimeModule();
    MyAtlIdeModule _myAtlIdeModule = new MyAtlIdeModule();
    return Guice.createInjector(Modules2.mixin(_myAtlRuntimeModule, _myAtlIdeModule));
  }
}
