/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myAtl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myAtl.BinaryOperatorCS;
import org.xtext.example.mydsl.myAtl.InfixExpCS;
import org.xtext.example.mydsl.myAtl.MyAtlPackage;
import org.xtext.example.mydsl.myAtl.PrefixedExpCS;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Infix Exp CS</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myAtl.impl.InfixExpCSImpl#getOwnedExpression <em>Owned Expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myAtl.impl.InfixExpCSImpl#getOwnedOperator <em>Owned Operator</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InfixExpCSImpl extends InfixedExpCSImpl implements InfixExpCS
{
  /**
   * The cached value of the '{@link #getOwnedExpression() <em>Owned Expression</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedExpression()
   * @generated
   * @ordered
   */
  protected EList<PrefixedExpCS> ownedExpression;

  /**
   * The cached value of the '{@link #getOwnedOperator() <em>Owned Operator</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedOperator()
   * @generated
   * @ordered
   */
  protected EList<BinaryOperatorCS> ownedOperator;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InfixExpCSImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyAtlPackage.Literals.INFIX_EXP_CS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<PrefixedExpCS> getOwnedExpression()
  {
    if (ownedExpression == null)
    {
      ownedExpression = new EObjectContainmentEList<PrefixedExpCS>(PrefixedExpCS.class, this, MyAtlPackage.INFIX_EXP_CS__OWNED_EXPRESSION);
    }
    return ownedExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<BinaryOperatorCS> getOwnedOperator()
  {
    if (ownedOperator == null)
    {
      ownedOperator = new EObjectContainmentEList<BinaryOperatorCS>(BinaryOperatorCS.class, this, MyAtlPackage.INFIX_EXP_CS__OWNED_OPERATOR);
    }
    return ownedOperator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyAtlPackage.INFIX_EXP_CS__OWNED_EXPRESSION:
        return ((InternalEList<?>)getOwnedExpression()).basicRemove(otherEnd, msgs);
      case MyAtlPackage.INFIX_EXP_CS__OWNED_OPERATOR:
        return ((InternalEList<?>)getOwnedOperator()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyAtlPackage.INFIX_EXP_CS__OWNED_EXPRESSION:
        return getOwnedExpression();
      case MyAtlPackage.INFIX_EXP_CS__OWNED_OPERATOR:
        return getOwnedOperator();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyAtlPackage.INFIX_EXP_CS__OWNED_EXPRESSION:
        getOwnedExpression().clear();
        getOwnedExpression().addAll((Collection<? extends PrefixedExpCS>)newValue);
        return;
      case MyAtlPackage.INFIX_EXP_CS__OWNED_OPERATOR:
        getOwnedOperator().clear();
        getOwnedOperator().addAll((Collection<? extends BinaryOperatorCS>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyAtlPackage.INFIX_EXP_CS__OWNED_EXPRESSION:
        getOwnedExpression().clear();
        return;
      case MyAtlPackage.INFIX_EXP_CS__OWNED_OPERATOR:
        getOwnedOperator().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyAtlPackage.INFIX_EXP_CS__OWNED_EXPRESSION:
        return ownedExpression != null && !ownedExpression.isEmpty();
      case MyAtlPackage.INFIX_EXP_CS__OWNED_OPERATOR:
        return ownedOperator != null && !ownedOperator.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //InfixExpCSImpl
