/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myAtl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myAtl.Module;
import org.xtext.example.mydsl.myAtl.ModuleElement;
import org.xtext.example.mydsl.myAtl.MyAtlPackage;
import org.xtext.example.mydsl.myAtl.NameExpCS;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Module</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myAtl.impl.ModuleImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myAtl.impl.ModuleImpl#getOutModels <em>Out Models</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myAtl.impl.ModuleImpl#getInModels <em>In Models</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myAtl.impl.ModuleImpl#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModuleImpl extends MinimalEObjectImpl.Container implements Module
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getOutModels() <em>Out Models</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOutModels()
   * @generated
   * @ordered
   */
  protected EList<NameExpCS> outModels;

  /**
   * The cached value of the '{@link #getInModels() <em>In Models</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInModels()
   * @generated
   * @ordered
   */
  protected EList<NameExpCS> inModels;

  /**
   * The cached value of the '{@link #getElements() <em>Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElements()
   * @generated
   * @ordered
   */
  protected EList<ModuleElement> elements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyAtlPackage.Literals.MODULE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyAtlPackage.MODULE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<NameExpCS> getOutModels()
  {
    if (outModels == null)
    {
      outModels = new EObjectContainmentEList<NameExpCS>(NameExpCS.class, this, MyAtlPackage.MODULE__OUT_MODELS);
    }
    return outModels;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<NameExpCS> getInModels()
  {
    if (inModels == null)
    {
      inModels = new EObjectContainmentEList<NameExpCS>(NameExpCS.class, this, MyAtlPackage.MODULE__IN_MODELS);
    }
    return inModels;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ModuleElement> getElements()
  {
    if (elements == null)
    {
      elements = new EObjectContainmentEList<ModuleElement>(ModuleElement.class, this, MyAtlPackage.MODULE__ELEMENTS);
    }
    return elements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyAtlPackage.MODULE__OUT_MODELS:
        return ((InternalEList<?>)getOutModels()).basicRemove(otherEnd, msgs);
      case MyAtlPackage.MODULE__IN_MODELS:
        return ((InternalEList<?>)getInModels()).basicRemove(otherEnd, msgs);
      case MyAtlPackage.MODULE__ELEMENTS:
        return ((InternalEList<?>)getElements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyAtlPackage.MODULE__NAME:
        return getName();
      case MyAtlPackage.MODULE__OUT_MODELS:
        return getOutModels();
      case MyAtlPackage.MODULE__IN_MODELS:
        return getInModels();
      case MyAtlPackage.MODULE__ELEMENTS:
        return getElements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyAtlPackage.MODULE__NAME:
        setName((String)newValue);
        return;
      case MyAtlPackage.MODULE__OUT_MODELS:
        getOutModels().clear();
        getOutModels().addAll((Collection<? extends NameExpCS>)newValue);
        return;
      case MyAtlPackage.MODULE__IN_MODELS:
        getInModels().clear();
        getInModels().addAll((Collection<? extends NameExpCS>)newValue);
        return;
      case MyAtlPackage.MODULE__ELEMENTS:
        getElements().clear();
        getElements().addAll((Collection<? extends ModuleElement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyAtlPackage.MODULE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyAtlPackage.MODULE__OUT_MODELS:
        getOutModels().clear();
        return;
      case MyAtlPackage.MODULE__IN_MODELS:
        getInModels().clear();
        return;
      case MyAtlPackage.MODULE__ELEMENTS:
        getElements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyAtlPackage.MODULE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyAtlPackage.MODULE__OUT_MODELS:
        return outModels != null && !outModels.isEmpty();
      case MyAtlPackage.MODULE__IN_MODELS:
        return inModels != null && !inModels.isEmpty();
      case MyAtlPackage.MODULE__ELEMENTS:
        return elements != null && !elements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ModuleImpl
