/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myATL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Infixed Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myATL.MyATLPackage#getInfixedExpCS()
 * @model
 * @generated
 */
public interface InfixedExpCS extends ExpCS
{
} // InfixedExpCS
