/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myATL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Literal Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myATL.StringLiteralExpCS#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myATL.MyATLPackage#getStringLiteralExpCS()
 * @model
 * @generated
 */
public interface StringLiteralExpCS extends PrimitiveLiteralExpCS
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute list.
   * @see org.xtext.example.mydsl.myATL.MyATLPackage#getStringLiteralExpCS_Name()
   * @model unique="false"
   * @generated
   */
  EList<String> getName();

} // StringLiteralExpCS
